#!/bin/bash

NC='\033[0m'
BRed='\033[1;31m'

REGEX_ISSUE_ID="[a-zA-Z0-9,._-]+-[0-9]+"
BRANCH_NAME=$(git symbolic-ref --short HEAD)
COMMIT_MESSAGE=$(cat "$1")



# Proíbe commits nas branches main e develop
if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "develop" ]; then
    echo -e "${BRed}Erro: Commits não são permitidos nas branches 'main' ou 'develop'.${NC}"
    exit 1
fi

# Verifica se a branch segue o padrão de Issue ID
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")

if [ -z "$ISSUE_ID" ]; then
    echo -e "${BRed}Erro: A branch não segue o padrão esperado. Um Issue ID deve estar presente na branch.${NC}"
    exit 1
fi

# Previne duplicação do Issue ID no commit
if echo "$COMMIT_MESSAGE" | grep -q "^$ISSUE_ID"; then
    exit 0
fi

# Prefixa o commit com o Issue ID
echo "$ISSUE_ID: $COMMIT_MESSAGE" > "$1"
